import fs from "node:fs";
import path from "node:path";

/**
 * Site-wide configuration read once at build time.
 *
 * Keep everything that isn't per-page or per-photo here so components
 * import a single stable object rather than reaching into env vars or
 * the filesystem themselves. Runs in Server Components / route
 * handlers only — NEVER import this from a client component (the
 * `node:fs` import will fail the client bundle).
 */

const PUBLIC_DIR = path.join(process.cwd(), "public");

/**
 * Filesystem-detect the brand logo.
 *
 * Priority:
 *   1. `/logo/logo-gold-transparent.svg` — hand-vectorised gold artwork
 *   2. `/logo/logo-gold-transparent.png` — generated by scripts/extract-gold.mjs
 *   3. `/logo.svg` / `/logo.png` / `/logo.jpg` — bare fallback in the repo root
 *
 * The transparent-gold variant is always preferred so the logo sits on
 * the gradient background without a dark rectangle behind it.
 */
function detectLogo(): { src: string; width?: number; height?: number } | null {
  const candidates = [
    "logo/logo-gold-transparent.svg",
    "logo/logo-gold-transparent.png",
    "logo.svg",
    "logo.png",
    "logo.jpg",
    "logo.jpeg",
    "logo.webp",
  ];
  for (const name of candidates) {
    if (fs.existsSync(path.join(PUBLIC_DIR, name))) {
      return { src: `/${name}` };
    }
  }
  return null;
}

export const SITE = {
  name: "VB Photographe",
  brandYear: "2015",
  location: "Salem, India",
  email: "vbphotograph2015@gmail.com",
  phones: ["+91 9789508944", "+91 9789508942"] as const,
  address: {
    lines: [
      "107, Ammapet Main Road",
      "Opp to Sri Soundharraja Perumal Temple",
      "Salem, Tamil Nadu 636001",
      "India",
    ] as const,
    /** Used to build the Google Maps link. */
    single:
      "107, Ammapet Main Road, Opp to Sri Soundharraja Perumal Temple, Salem, Tamil Nadu 636001, India",
  },
  logo: detectLogo(),
  social: {
    instagram: {
      handle: "vbphotographe",
      href: "https://www.instagram.com/vbphotographe",
    },
    google: {
      reviewHref: "https://g.page/r/CcyTEASvalHlEAE/review",
      businessName: "VB Photographe",
    },
  },
} as const;

export type Site = typeof SITE;
